# -*- coding: utf-8 -*-
"""Trần Thị Hồng Nhi | RFM analysis project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ZeZjgeD_i1CcEqa7KiFpEsVXjMBNCXG
"""

#import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive/')
path = '/content/drive/MyDrive/Colab Notebooks | Python DAC/RFM project/ecommerce retail.xlsx'

ecommerce_retail = pd.read_excel("/content/drive/MyDrive/Colab Notebooks | Python DAC/RFM project/ecommerce retail.xlsx")

ecommerce_retail.head()

ecommerce_retail.info()

ecommerce_retail['InvoiceDate'] = pd.to_datetime(ecommerce_retail['InvoiceDate'])

ecommerce_retail.info()

ecommerce_retail.describe()

ecommerce_retail['InvoiceNo'].value_counts()

df_valid = ecommerce_retail[(~ecommerce_retail['InvoiceNo'].str.startswith('C', na=False))
                             & (ecommerce_retail['Quantity'] >0)
                             & (ecommerce_retail['UnitPrice'] >0)
                           ]

df_valid.info()

#Tỷ lệ số dòng dữ liệu null CusID
missing_customers = df_valid['CustomerID'].isnull().value_counts(normalize=True)
missing_customers

check_null_CusID = df_valid.copy()
check_null_CusID['Revenue'] = check_null_CusID['Quantity'] * check_null_CusID['UnitPrice']

revenue_null = check_null_CusID.loc[check_null_CusID['CustomerID'].isnull(), 'Revenue'].sum()

revenue_total = check_null_CusID['Revenue'].sum()

nullrevenue_ratio = revenue_null/revenue_total*100
nullrevenue_ratio # > 5% nên không loại bỏ được, ảnh hưởng tới dữ liệu nhưng sẽ tách riêng

df_valid['CustomerID'].value_counts()

df_valid['Country'].value_counts(sort=True)

revenue_each_country = check_null_CusID.groupby('Country')['Revenue'].sum().sort_values(ascending=False).reset_index()
revenue_each_country

uk_vs_nonuk = pd.DataFrame({
    'Market': ['United Kingdom', 'Non-UK'],
    'Revenue': [revenue_each_country[revenue_each_country['Country']=='United Kingdom']['Revenue'].sum(),
                revenue_each_country[revenue_each_country['Country']!='United Kingdom']['Revenue'].sum()]
})

plt.figure(figsize=(5,5))
plt.pie(uk_vs_nonuk['Revenue'], labels=uk_vs_nonuk['Market'], autopct='%1.1f%%', startangle=90, colors=['#41B6C4', '#EDF8B1'])
plt.title('UK vs Non-UK Revenue Share', fontsize=12, weight='bold')
plt.savefig('Pie Chart - UK vs Non-UK Revenue Share.jpg', dpi=400, bbox_inches='tight')
plt.show()

# from google.colab import files
# files.download('Pie Chart - UK vs Non-UK Revenue Share.jpg')

sns.barplot(revenue_each_country.head(10), x='Country', y='Revenue', color='navy')

plt.title('Top 10 Coutries With The Largest Revenue', weight='bold')
plt.xticks(rotation=90)
plt.xlabel('')
plt.savefig('Top_10_countries.jpg', dpi=300, bbox_inches = 'tight')
plt.show()

# from google.colab import files
# files.download('Top_10_countries.jpg')

sns.barplot(revenue_each_country[revenue_each_country['Country']!='United Kingdom'].head(10), x='Country', y='Revenue', color='navy')

plt.title('Top 10 Non-UK Coutries With The Largest Revenue', weight='bold')
plt.xticks(rotation=90)
plt.xlabel('')
plt.savefig('Top_10_nonuk_countries.jpg', dpi=300, bbox_inches = 'tight')
plt.show()

# files.download('Top_10_nonuk_countries.jpg')

"""# **A. UK-MARKET ANALYSIS**"""

#Get rid of null CustomerID
ecommerce_retail_uk = df_valid[(df_valid['Country']=='United Kingdom') & (df_valid['CustomerID'].notnull())]
ecommerce_retail_uk.info()

"""# **1. Recency**"""

df_uk_max_purchasing_date = ecommerce_retail_uk.groupby('CustomerID')['InvoiceDate'].max().reset_index()
df_uk_max_purchasing_date.columns = ['CustomerID','MaxPurchasingDate']
df_uk_max_purchasing_date.head()

#Ngày tính của chỉ số R tính vào ngày 31/12/2011
df_uk_max_purchasing_date['Recency'] = (pd.to_datetime("2011-12-31") - df_uk_max_purchasing_date['MaxPurchasingDate']).dt.days
df_uk_max_purchasing_date.head()

df_uk_max_purchasing_date.info()

ecommerce_retail_uk['CustomerID'].nunique()

"""# **2. Frequency**"""

ecommerce_retail_uk.head()

df_uk_frequency = ecommerce_retail_uk.groupby('CustomerID')['InvoiceNo'].nunique().reset_index()

df_uk_frequency.columns = ['CustomerID','Frequency']
df_uk_frequency.head()

"""# **3. Monetary**"""

ecommerce_retail_uk['TotalRevenue'] = ecommerce_retail_uk['Quantity'] * ecommerce_retail_uk['UnitPrice']

ecommerce_retail_uk.head()

df_uk_monetary = ecommerce_retail_uk.groupby('CustomerID')['TotalRevenue'].sum().reset_index()
df_uk_monetary.head()

df_uk_monetary.columns = ['CustomerID', 'Monetary']

df_uk_max_purchasing_date.head()

df_uk_frequency.head()

df_uk_monetary.head()

df_uk_rfm = (df_uk_max_purchasing_date[['CustomerID','Recency']].merge(df_uk_frequency,on='CustomerID')).merge(df_uk_monetary, on='CustomerID')
df_uk_rfm.head(10)

df_uk_rfm.info()

#Recency
df_uk_rfm['R'] = pd.qcut(df_uk_rfm['Recency'], 5, labels=[5,4,3,2,1]).astype(str)

#Frequency
df_uk_rfm['F'] = pd.qcut(df_uk_rfm['Frequency'].rank(method='first'), 5, labels=[1,2,3,4,5]).astype(str)

#Monetary
df_uk_rfm['M'] = pd.qcut(df_uk_rfm['Monetary'],5,labels=[1,2,3,4,5]).astype(str)

df_uk_rfm

df_uk_rfm['RFM_score_uk'] = df_uk_rfm['R'].astype(str) + df_uk_rfm['F'].astype(str) + df_uk_rfm['M'].astype(str)

df_uk_rfm

mapping_seg = pd.read_excel(path, sheet_name = 'Segmentation')

mapping_seg.info()

mapping_seg

mapping_seg['RFM Score'] = mapping_seg['RFM Score'].str.replace(' ','').str.split(',')

segmentation_dct = dict(zip(mapping_seg['Segment'],mapping_seg['RFM Score']))

segmentation_dct

segmentation_dct.items()

df_seg = pd.DataFrame([
    {'Segment': seg_name, 'RFM_Score_chuan': ','.join(score)}
    for seg_name, score in segmentation_dct.items()
])

df_seg

df_seg['RFM_Score_chuan'] = df_seg['RFM_Score_chuan'].str.split(',')

df_seg = df_seg.explode('RFM_Score_chuan').reset_index(drop=True)

df_seg

df_uk_rfm

df_uk_rfm = pd.merge(df_uk_rfm,df_seg, how='left', left_on='RFM_score_uk', right_on='RFM_Score_chuan')

df_uk_rfm

df_uk_rfm.drop('RFM_Score_chuan', axis=1, inplace=True)

df_uk_rfm

ecommerce_retail_uk['InvoiceYearMonth'] = ecommerce_retail_uk['InvoiceDate'].dt.strftime('%Y-%m')

ecommerce_retail_uk

revenue_monthly = ecommerce_retail_uk.groupby('InvoiceYearMonth')['TotalRevenue'].sum().reset_index()
revenue_monthly

plt.figure(figsize=(12,5))
sns.lineplot(data=revenue_monthly, x='InvoiceYearMonth', y='TotalRevenue', marker='o', color='navy') #'#2E3A8C'

plt.title('Revenue Trend Over Time', fontsize=12, fontweight='bold')
plt.xlabel('')
plt.ylabel('Total Revenue')

plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('Revenue Trend Over Time.jpg', dpi=300, bbox_inches = 'tight')
plt.show()

# files.download('Revenue Trend Over Time.jpg')

segment_order = [
    "Champions", "Loyal", "Potential Loyalist",
    "New Customers", "Promising", "Need Attention",
    "About To Sleep", "At Risk", "Cannot Lose Them",
    "Hibernating customers", "Lost customers"]

sns.set_style('whitegrid')
sns.countplot(x='Segment', data= df_uk_rfm, order = segment_order, palette= 'YlGnBu_r')
plt.title('Customer Count by Segment (Ordered by Lifecycle)', weight='bold')
plt.xticks(rotation=90)

plt.savefig('Customer Count by Segment.jpg', dpi=300, bbox_inches = 'tight')
plt.show()

# files.download('Customer Count by Segment.jpg')

rfm_heatmap = df_uk_rfm.pivot_table(index='R', columns='F', values='Monetary', aggfunc='mean')

rfm_heatmap

plt.figure(figsize=(8,5))
sns.heatmap(rfm_heatmap, cmap='YlGnBu', annot=True, fmt='.0f')
plt.title('Average Monetary by R and F', weight='bold')
plt.xlabel('Frequency Score (F)')
plt.ylabel('Recency Score (R)')
plt.savefig('Heatmap.jpg', dpi=300, bbox_inches='tight')
plt.show()

# files.download('Heatmap.jpg')

plt.figure(figsize=(9,6))
sns.scatterplot(data= df_uk_rfm, x= 'Recency', y='Monetary', hue='Segment', hue_order= segment_order,palette= 'YlGnBu_r')
plt.title('Recency vs Monetary by Segment', fontsize=12, weight = 'bold')
plt.savefig('Scatter.jpg', dpi=300, bbox_inches='tight')
plt.show()

# files.download('Scatter.jpg')

# data=df_uk_rfm['Recency'].plot.hist()
# plt.show()

sns.histplot(data=df_uk_rfm['Recency'],color='navy')
plt.title('Distribution of Recency')
plt.savefig('Distribution R.jpg', dpi=300, bbox_inches='tight')
plt.show()

# files.download('Distribution R.jpg')

sns.displot(data=df_uk_rfm['Monetary'], color='Navy')

plt.title('Distribution of Monetary')
plt.savefig('Distribution M.jpg', dpi=300, bbox_inches='tight')

# files.download('Distribution M.jpg')

sns.displot(data=df_uk_rfm['Frequency'], color='Navy')

plt.title('Distribution of Frequency')
plt.savefig('Distribution F.jpg', dpi=300, bbox_inches='tight')
plt.show()

# files.download('Distribution F.jpg')

sns.boxplot(data=df_uk_rfm, x='Segment', y='Frequency', order=segment_order)
plt.xticks(rotation=90)
plt.show()

sns.boxplot(data=df_uk_rfm, x='Segment', y='Recency', order=segment_order, color='navy')
plt.xticks(rotation=90)
plt.title('The boxplot of Recency by Segment')
plt.xlabel('')
plt.savefig('boxplot R.jpg', dpi=300, bbox_inches='tight')

# files.download('boxplot R.jpg')

rfm_uk_monetary = df_uk_rfm.groupby('Segment')['Monetary'].agg(['sum','mean']).reset_index()
rfm_uk_monetary.columns = ['Segment','TotalRevenue','AvgRevenue']

rfm_uk_monetary

plt.figure(figsize=(8,5))
sns.set_style('whitegrid')
sns.barplot(data=rfm_uk_monetary, y='Segment', x='TotalRevenue', order=segment_order, width=0.85, palette='YlGnBu_r')

# for i, v in enumerate(rfm_uk_monetary['TotalRevenue']):
#     plt.text(v, i, f'{v:,.0f}', va='center', fontsize=9)

plt.title('Total Revenue by Customer Segment', fontsize=12, weight = 'bold')
plt.xlabel('Total Revenue')
plt.ylabel('')
plt.tight_layout()
plt.savefig('Total Rev by Seg.jpg', dpi=300, bbox_inches='tight')
plt.show()

# files.download('Total Rev by Seg.jpg')

fig, ax = plt.subplots(figsize=(8,5))
sns.set_style('whitegrid')
sns.barplot(data=rfm_uk_monetary, y='Segment', x='AvgRevenue', order=segment_order, width=0.85, palette='YlGnBu_r')

# for i, v in enumerate(rfm_uk_monetary['AvgRevenue']):
#   ax.text(v + (max(rfm_uk_monetary['AvgRevenue']) * 0.03), i, f'{v:,.0f}', va='center', ha='right')

plt.title('Average Revenue by Customer Segment', fontsize=12, weight = 'bold')
plt.xlabel('Average Revenue')
plt.ylabel('')
plt.tight_layout()
plt.savefig('Avg Rev by Seg.jpg', dpi=300, bbox_inches='tight')
plt.show()

# files.download('Avg Rev by Seg.jpg')

rfm_uk_monetary

rfm_uk_monetary['Proportion_%Rev'] = rfm_uk_monetary['TotalRevenue'] / rfm_uk_monetary['TotalRevenue'].sum()*100

rfm_uk_monetary

!pip install squarify

import squarify
import numpy as np

colors = plt.cm.YlGnBu(np.linspace(0, 1, 11))

plt.figure(figsize=(10, 8))
squarify.plot(
    sizes=rfm_uk_monetary['Proportion_%Rev'],
    label=rfm_uk_monetary['Segment'],
    color=colors,
    alpha=0.8,
    text_kwargs={'fontsize': 7}
)
plt.title('Proportion of Revenue by Segment', fontsize=12, weight='bold')
plt.axis('off')
plt.savefig('treemap.jpg', dpi=300, bbox_inches='tight')
plt.show()

# files.download('treemap.jpg')

"""# **B. Non-UK Market Analysis**"""

df_valid

ecommerce_retail_nonuk = df_valid[(df_valid['Country']!='United Kingdom') & (df_valid['CustomerID'].notnull())]
ecommerce_retail_nonuk

df_nonuk_max_purchasing_date = ecommerce_retail_nonuk.groupby('CustomerID')['InvoiceDate'].max().reset_index()
df_nonuk_max_purchasing_date.columns = ['CustomerID','MaxPurchasingDate']

#Ngày tính của chỉ số R tính vào ngày 31/12/2011
df_nonuk_max_purchasing_date['Recency'] = (pd.to_datetime("2011-12-31") - df_uk_max_purchasing_date['MaxPurchasingDate']).dt.days
df_nonuk_max_purchasing_date

df_nonuk_frequency = ecommerce_retail_nonuk.groupby('CustomerID')['InvoiceNo'].nunique().reset_index()
df_nonuk_frequency.columns = ['CustomerID', 'Frequency']
df_nonuk_frequency

ecommerce_retail_nonuk['TotalRevenue'] = ecommerce_retail_nonuk['Quantity'] * ecommerce_retail_nonuk['UnitPrice']

df_nonuk_monetary = ecommerce_retail_nonuk.groupby('CustomerID')['TotalRevenue'].sum().reset_index()

df_nonuk_monetary.columns = ['CustomerID','Monetary']

df_nonuk_rfm = (df_nonuk_max_purchasing_date[['CustomerID','Recency']].merge(df_nonuk_frequency,on='CustomerID')).merge(df_nonuk_monetary, on='CustomerID')
df_nonuk_rfm

#Recency
df_nonuk_rfm['R'] = pd.qcut(df_nonuk_rfm['Recency'], 5, labels=[5,4,3,2,1]).astype(str)
#Frequency
df_nonuk_rfm['F'] = pd.qcut(df_nonuk_rfm['Frequency'].rank(method='first'), 5, labels=[1,2,3,4,5]).astype(str)
#Monetary
df_nonuk_rfm['M'] = pd.qcut(df_nonuk_rfm['Monetary'],5,labels=[1,2,3,4,5]).astype(str)

df_nonuk_rfm['RFM_score_nonuk'] = df_nonuk_rfm['R'].astype(str) + df_nonuk_rfm['F'].astype(str) + df_nonuk_rfm['M'].astype(str)
df_nonuk_rfm = pd.merge(df_nonuk_rfm,df_seg, how='left', left_on='RFM_score_nonuk', right_on='RFM_Score_chuan')
df_nonuk_rfm.drop('RFM_Score_chuan', axis=1, inplace=True)
df_nonuk_rfm

sns.countplot(x='Segment', data= df_nonuk_rfm, order = segment_order, palette= 'YlGnBu_r')
plt.title('Customer Count by Segment on Non-UK Market', weight='bold')
plt.xticks(rotation=90)
plt.xlabel('')

plt.savefig('Customer Count by Segment on Non-UK Market.jpg', dpi=300, bbox_inches = 'tight')
plt.show()

# files.download('Customer Count by Segment on Non-UK Market.jpg')

rfm_nonuk_monetary = df_nonuk_rfm.groupby('Segment')['Monetary'].sum().reset_index()

plt.figure(figsize=(8,5))

sns.barplot(data=rfm_nonuk_monetary, y='Segment', x='Monetary', order=segment_order, width=0.85, palette='YlGnBu_r')

plt.title('Total Revenue by Customer Segment on Non-UK Market', fontsize=12, weight = 'bold')
plt.xlabel('Total Revenue')
plt.ylabel('')
plt.tight_layout()
plt.savefig('Total Rev by Seg on Non-UK Market.jpg', dpi=300, bbox_inches='tight')
plt.show()

# files.download('Total Rev by Seg on Non-UK Market.jpg')

plt.figure(figsize=(10, 8))
squarify.plot(
    sizes=rfm_nonuk_monetary['Monetary'],
    label=rfm_nonuk_monetary['Segment'],
    color=colors,
    alpha=0.8,
    text_kwargs={'fontsize': 7}
)
plt.title('Total Revenue by Segment', fontsize=12, weight='bold')
plt.axis('off')
plt.savefig('treemap.jpg', dpi=300, bbox_inches='tight')
plt.show()